from flexrouter.recovery import PenaltyBox
import time

print("=" * 60)
print("BUG #1: penalty_seconds returns incorrect value when not penalized")
print("=" * 60)
pb = PenaltyBox(base_seconds=30, max_seconds=1800)
# Never penalized: count=0 in _state.get(k, (0.0, 0)) returns 0
# penalty_seconds for count=0: min(30 * 2^(-1), 1800) = min(15.0, 1800) = 15.0
result = pb.penalty_seconds('x', 'y')
print(f"penalty_seconds('x', 'y') when never penalized: {result}")
print(f"Expected: probably 0 (or base_seconds 30), not 15.0 (half of base)")
print(f"Issue: formula uses 2^(count-1) which gives 2^(-1) = 0.5 when count=0")
print()

print("=" * 60)
print("BUG #2: penalty_seconds doesn't check expiration")
print("=" * 60)
pb2 = PenaltyBox(base_seconds=1, max_seconds=10)
pb2.penalize("a", "b")
time.sleep(1.1)
# After expiration, is_penalized correctly returns False
print(f"is_penalized (after expiration): {pb2.is_penalized('a', 'b')}")
# But penalty_seconds still computes from the old count
print(f"penalty_seconds (after expiration): {pb2.penalty_seconds('a', 'b')}")
print(f"Expected: should be 0 or indicate expired, not return stale penalty duration")
print()

print("=" * 60)
print("BUG #3: penalty_until could return stale value")
print("=" * 60)
pb3 = PenaltyBox(base_seconds=1, max_seconds=10)
pb3.penalize("a", "b")
time.sleep(1.1)
# After expiration, penalty_until correctly returns None
result = pb3.penalty_until('a', 'b')
print(f"penalty_until (after expiration): {result}")
print(f"This is correct - returns None as penalty expired")
print()

print("=" * 60)
print("SPEC COMPLIANCE CHECK")
print("=" * 60)
print("Method signatures - all present and correct")
print("✓ __init__(base_seconds, max_seconds)")
print("✓ penalize(provider, model)")
print("✓ penalize_short(provider, model, seconds)")
print("✓ clear(provider, model)")
print("✓ is_penalized(provider, model) -> bool")
print("✓ penalty_seconds(provider, model) -> int")
print("✓ penalty_until(provider, model) -> Optional[float]")
print()
print("Exponential backoff formula:")
print("✓ base * 2^(count-1) - mathematically correct")
print("✓ capped at max - correct")
print("✓ count incremented on each penalize() call - correct")
print()
print("ISSUES:")
print("✗ penalty_seconds returns float (15.0) when it should return int")
print("✗ penalty_seconds returns wrong value when not penalized (should be 0?)")
print("✗ penalty_seconds doesn't check if penalty has expired")
print("✗ penalty_until's comment says 'monotonic timestamp' but returns float timestamp")
